apiVersion: apps/v1
kind: Deployment
metadata:
  name: supergiros-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supergiros-api
  template:
    metadata:
      labels:
        app: supergiros-api
    spec:
      containers:
      - name: supergiros-api
        image: supergirostransfer-api:latest # El nombre exacto de la imagen local generada por tu Docker
        imagePullPolicy: Never # Evita que busque la imagen en Internet, forzando el uso del entorno local
        ports:
        - containerPort: 5240   # HTTP1 / Swagger / gRPC-Web
        - containerPort: 5241   # HTTP2 / gRPC Nativo Puro
        env:
        # Inyecta los puertos nativos para que Kestrel los reconozca dentro del Pod
        - name: ASPNETCORE_URLS
          value: "http://+:5240;http://+:5241"
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: supergiros-config
              key: ASPNETCORE_ENVIRONMENT
        - name: JwtSettings__Issuer
          valueFrom:
            configMapKeyRef:
              name: supergiros-config
              key: JwtSettings__Issuer
        - name: JwtSettings__Audience
          valueFrom:
            configMapKeyRef:
              name: supergiros-config
              key: JwtSettings__Audience
        - name: JwtSettings__ExpirationHours
          valueFrom:
            configMapKeyRef:
              name: supergiros-config
              key: JwtSettings__ExpirationHours
        - name: CorsSettings__AllowedOrigins__0
          valueFrom:
            configMapKeyRef:
              name: supergiros-config
              key: CorsSettings__AllowedOrigins__0
        - name: ConnectionStrings__TransferConnection
          valueFrom:
            secretKeyRef:
              name: supergiros-secrets
              key: db-connection
        - name: JwtSettings__SecretKey
          valueFrom:
            secretKeyRef:
              name: supergiros-secrets
              key: jwt-secret
        readinessProbe:
          httpGet:
            path: / # Golpea el endpoint "/" configurado en tu Program.cs
            port: 5240
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: supergiros-api-svc
  namespace: default
spec:
  selector:
    app: supergiros-api
  ports:
  - name: http
    port: 5240
    targetPort: 5240
    nodePort: 30220             # Puerto externo para Swagger / REST / gRPC-Web en Windows
  - name: grpc
    port: 5241
    targetPort: 5241
    nodePort: 30221             # Puerto externo exclusivo para llamadas gRPC binarias puras
  type: NodePort