apiVersion: apps/v1
kind: Deployment
metadata:
  name: supergiros-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supergiros-api
  template:
    metadata:
      labels:
        app: supergiros-api
    spec:
      containers:
      - name: supergiros-api
        image: supergiros-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5240   # HTTP1 / Swagger
        - containerPort: 5241   # HTTP2 / gRPC
        env:
        # 🌟 VITAL: Esto le ordena a .NET en Docker respetar tus dos puertos nativos
        - name: ASPNETCORE_URLS
          value: "http://+:5240;http://+:5241"
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: supergiros-config
              key: ASPNETCORE_ENVIRONMENT
        - name: JwtSettings__Issuer
          valueFrom:
            configMapKeyRef:
              name: supergiros-config
              key: JwtSettings__Issuer
        - name: JwtSettings__Audience
          valueFrom:
            configMapKeyRef:
              name: supergiros-config
              key: JwtSettings__Audience
        - name: JwtSettings__ExpirationHours
          valueFrom:
            configMapKeyRef:
              name: supergiros-config
              key: JwtSettings__ExpirationHours
        - name: ConnectionStrings__TransferConnection
          valueFrom:
            secretKeyRef:
              name: supergiros-secrets
              key: db-connection
        - name: JwtSettings__SecretKey
          valueFrom:
            secretKeyRef:
              name: supergiros-secrets
              key: jwt-secret
        readinessProbe:
          httpGet:
            path: /
            port: 5240          # Golpea el puerto HTTP1 para saber si está vivo
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: supergiros-api-svc
  namespace: default
spec:
  selector:
    app: supergiros-api
  ports:
  - name: http
    port: 5240
    targetPort: 5240
    nodePort: 30220             # Tu puerto externo para Swagger / REST
  - name: grpc
    port: 5241
    targetPort: 5241
    nodePort: 30221             # Tu puerto externo exclusivo para el tráfico gRPC binario
  type: NodePort