apiVersion: v1
kind: ConfigMap
metadata:
  name: supergiros-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  JwtSettings__Issuer: "SuperGiros.Transfer.API"
  JwtSettings__Audience: "SuperGiros.Transfer.Users"
  JwtSettings__ExpirationHours: "1"
  MSSQL_PID: "Express"
  # URL del Frontend de React para el control de políticas de CORS
  CorsSettings__AllowedOrigins__0: "http://localhost:5173"